// ITSM Operations — Document Generator
// Generates professional documents for ITSM workflows.
//
// Currently returns structured markdown so no extra npm dependencies are needed.
// The API is designed so real doc generation (docx, exceljs, pptxgenjs) can be
// plugged in later by replacing the body of each method.

// ── Types ──

export interface DocResult {
  content: string;
  format: 'markdown';
  suggestedFilename: string;
}

export interface ChangeData {
  changeId: string;
  title: string;
  description: string;
  type: string;
  riskScore: number;
  impactedCIs: string[];
  rollbackPlan: string;
  implementationPlan: string;
  scheduledStart: string;
  scheduledEnd: string;
  requestedBy: string;
  cabRecommendation?: string;
}

export interface IncidentData {
  incidentId: string;
  title: string;
  severity: string;
  timeline: Array<{ time: string; event: string }>;
  rootCause: string;
  resolution: string;
  impactSummary: string;
  lessonsLearned: string[];
  actionItems: Array<{ owner: string; action: string; dueDate: string }>;
}

export interface ServiceReviewMetrics {
  period: string;
  incidentCount: number;
  mttr: string;
  slaCompliance: number;
  changeSuccessRate: number;
  problemsResolved: number;
  topCategories: Array<{ category: string; count: number }>;
  highlights: string[];
  risks: string[];
}

export interface RiskEntry {
  id: string;
  description: string;
  likelihood: number;
  impact: number;
  score: number;
  mitigation: string;
  owner: string;
  status: string;
}

export interface DRTestData {
  drillId: string;
  date: string;
  scenario: string;
  participantsCount: number;
  rtoTarget: string;
  rtoActual: string;
  rpoTarget: string;
  rpoActual: string;
  findings: Array<{ severity: string; finding: string; recommendation: string }>;
  overallResult: 'pass' | 'partial' | 'fail';
}

export interface KPIData {
  period: string;
  metrics: Array<{
    name: string;
    target: number;
    actual: number;
    unit: string;
    trend: 'up' | 'down' | 'stable';
  }>;
}

// ── Generator ──

export class DocGenerator {
  /**
   * Generate an RFC (Request for Change) document.
   */
  generateChangeRFC(data: ChangeData): DocResult {
    const riskLabel = data.riskScore >= 8 ? 'HIGH' : data.riskScore >= 5 ? 'MEDIUM' : 'LOW';
    const content = `# Request for Change — ${data.changeId}

## Change Details
| Field | Value |
|-------|-------|
| **Change ID** | ${data.changeId} |
| **Title** | ${data.title} |
| **Type** | ${data.type} |
| **Requested By** | ${data.requestedBy} |
| **Scheduled Start** | ${data.scheduledStart} |
| **Scheduled End** | ${data.scheduledEnd} |

## Description
${data.description}

## Risk Assessment
- **Risk Score:** ${data.riskScore}/10 (${riskLabel})
- **Impacted CIs:** ${data.impactedCIs.join(', ')}

## Implementation Plan
${data.implementationPlan}

## Rollback Plan
${data.rollbackPlan}

## CAB Recommendation
${data.cabRecommendation || '_Pending CAB review_'}

---
_Generated by ITSM Operations Digital Worker — ${new Date().toISOString()}_
`;
    return { content, format: 'markdown', suggestedFilename: `RFC-${data.changeId}.md` };
  }

  /**
   * Generate a post-incident review report.
   */
  generateIncidentReport(data: IncidentData): DocResult {
    const timelineRows = data.timeline
      .map((t) => `| ${t.time} | ${t.event} |`)
      .join('\n');
    const actionRows = data.actionItems
      .map((a) => `| ${a.owner} | ${a.action} | ${a.dueDate} |`)
      .join('\n');
    const lessons = data.lessonsLearned.map((l) => `- ${l}`).join('\n');

    const content = `# Post-Incident Review — ${data.incidentId}

## Incident Summary
| Field | Value |
|-------|-------|
| **Incident ID** | ${data.incidentId} |
| **Title** | ${data.title} |
| **Severity** | ${data.severity} |

## Impact Summary
${data.impactSummary}

## Timeline
| Time | Event |
|------|-------|
${timelineRows}

## Root Cause Analysis
${data.rootCause}

## Resolution
${data.resolution}

## Lessons Learned
${lessons}

## Action Items
| Owner | Action | Due Date |
|-------|--------|----------|
${actionRows}

---
_Generated by ITSM Operations Digital Worker — ${new Date().toISOString()}_
`;
    return { content, format: 'markdown', suggestedFilename: `PIR-${data.incidentId}.md` };
  }

  /**
   * Generate a monthly service review deck (markdown representation).
   */
  generateServiceReviewPack(period: string, metrics: ServiceReviewMetrics): DocResult {
    const categoryRows = metrics.topCategories
      .map((c) => `| ${c.category} | ${c.count} |`)
      .join('\n');
    const highlights = metrics.highlights.map((h) => `- ✅ ${h}`).join('\n');
    const risks = metrics.risks.map((r) => `- ⚠️ ${r}`).join('\n');

    const content = `# Monthly Service Review — ${period}

## Executive Summary
| KPI | Value |
|-----|-------|
| **Incident Count** | ${metrics.incidentCount} |
| **Mean Time to Resolve** | ${metrics.mttr} |
| **SLA Compliance** | ${metrics.slaCompliance}% |
| **Change Success Rate** | ${metrics.changeSuccessRate}% |
| **Problems Resolved** | ${metrics.problemsResolved} |

## Top Incident Categories
| Category | Count |
|----------|-------|
${categoryRows}

## Highlights
${highlights}

## Risks & Concerns
${risks}

---
_Generated by ITSM Operations Digital Worker — ${new Date().toISOString()}_
`;
    return { content, format: 'markdown', suggestedFilename: `ServiceReview-${period}.md` };
  }

  /**
   * Generate a risk register / heatmap document.
   */
  generateRiskHeatmap(riskData: RiskEntry[]): DocResult {
    const rows = riskData
      .sort((a, b) => b.score - a.score)
      .map(
        (r) =>
          `| ${r.id} | ${r.description} | ${r.likelihood} | ${r.impact} | **${r.score}** | ${r.status} | ${r.owner} |`
      )
      .join('\n');

    const content = `# Risk Register & Heatmap

## Risk Matrix
| ID | Description | Likelihood (1-5) | Impact (1-5) | Score | Status | Owner |
|----|-------------|:-----------------:|:------------:|:-----:|--------|-------|
${rows}

## Heatmap Legend
- **20-25:** 🔴 Critical — Immediate action required
- **12-19:** 🟠 High — Action plan needed within 7 days
- **6-11:** 🟡 Medium — Monitor and review monthly
- **1-5:** 🟢 Low — Accept or monitor quarterly

---
_Generated by ITSM Operations Digital Worker — ${new Date().toISOString()}_
`;
    return { content, format: 'markdown', suggestedFilename: `RiskRegister-${new Date().toISOString().slice(0, 10)}.md` };
  }

  /**
   * Generate a CAB meeting agenda.
   */
  generateCABAgenda(changes: ChangeData[]): DocResult {
    const rfcRows = changes
      .map(
        (c) =>
          `| ${c.changeId} | ${c.title} | ${c.type} | ${c.riskScore}/10 | ${c.scheduledStart} |`
      )
      .join('\n');

    const content = `# Change Advisory Board — Agenda

**Date:** ${new Date().toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}

## 1. Review of Previous Actions
_[Actions from last CAB meeting]_

## 2. Changes for Review (${changes.length})
| Change ID | Title | Type | Risk | Scheduled |
|-----------|-------|------|:----:|-----------|
${rfcRows}

## 3. Emergency Changes (Retrospective)
_[Any emergency changes implemented since last CAB]_

## 4. Failed Changes Review
_[Post-implementation review of failed changes]_

## 5. Forward Schedule of Change
_[Upcoming change freeze periods and key dates]_

## 6. AOB

---
_Generated by ITSM Operations Digital Worker — ${new Date().toISOString()}_
`;
    return { content, format: 'markdown', suggestedFilename: `CAB-Agenda-${new Date().toISOString().slice(0, 10)}.md` };
  }

  /**
   * Generate a KPI dashboard document.
   */
  generateKPIDashboard(kpiData: KPIData): DocResult {
    const trendIcon = (t: string) => (t === 'up' ? '📈' : t === 'down' ? '📉' : '➡️');
    const rows = kpiData.metrics
      .map(
        (m) =>
          `| ${m.name} | ${m.actual} ${m.unit} | ${m.target} ${m.unit} | ${m.actual >= m.target ? '✅' : '❌'} | ${trendIcon(m.trend)} |`
      )
      .join('\n');

    const content = `# KPI Dashboard — ${kpiData.period}

| Metric | Actual | Target | Status | Trend |
|--------|:------:|:------:|:------:|:-----:|
${rows}

---
_Generated by ITSM Operations Digital Worker — ${new Date().toISOString()}_
`;
    return { content, format: 'markdown', suggestedFilename: `KPI-Dashboard-${kpiData.period}.md` };
  }

  /**
   * Generate a DR (Disaster Recovery) drill test report.
   */
  generateDRTestReport(data: DRTestData): DocResult {
    const resultEmoji = data.overallResult === 'pass' ? '✅ PASS' : data.overallResult === 'partial' ? '⚠️ PARTIAL' : '❌ FAIL';
    const findingRows = data.findings
      .map((f) => `| ${f.severity} | ${f.finding} | ${f.recommendation} |`)
      .join('\n');

    const content = `# DR Drill Report — ${data.drillId}

## Drill Summary
| Field | Value |
|-------|-------|
| **Drill ID** | ${data.drillId} |
| **Date** | ${data.date} |
| **Scenario** | ${data.scenario} |
| **Participants** | ${data.participantsCount} |
| **Overall Result** | ${resultEmoji} |

## Recovery Objectives
| Metric | Target | Actual | Met? |
|--------|--------|--------|:----:|
| **RTO** | ${data.rtoTarget} | ${data.rtoActual} | ${data.rtoActual <= data.rtoTarget ? '✅' : '❌'} |
| **RPO** | ${data.rpoTarget} | ${data.rpoActual} | ${data.rpoActual <= data.rpoTarget ? '✅' : '❌'} |

## Findings
| Severity | Finding | Recommendation |
|----------|---------|----------------|
${findingRows}

---
_Generated by ITSM Operations Digital Worker — ${new Date().toISOString()}_
`;
    return { content, format: 'markdown', suggestedFilename: `DR-Report-${data.drillId}.md` };
  }
}

export const docGenerator = new DocGenerator();
