/**
 * Microsoft Graph Mail — Send emails as the agent identity.
 * Replaces custom SMTP-based email-service.ts with Graph API.
 * 
 * Supports HTML templates, read receipts, attachments, and
 * send-as capability using the agent's application identity.
 */

import { Client } from '@microsoft/microsoft-graph-client';
import { TokenCredentialAuthenticationProvider } from '@microsoft/microsoft-graph-client/authProviders/azureTokenCredentials';
import { DefaultAzureCredential } from '@azure/identity';

// ── Configuration ──
const GRAPH_SENDER = process.env.GRAPH_MAIL_SENDER || ''; // UPN or object ID of sending user/mailbox
const GRAPH_SCOPES = ['https://graph.microsoft.com/.default'];

let graphClient: Client | null = null;

// ── Types ──
export interface EmailMessage {
  to: string[];
  cc?: string[];
  subject: string;
  body: string;
  isHtml?: boolean;
  importance?: 'low' | 'normal' | 'high';
  requestReadReceipt?: boolean;
  attachments?: EmailAttachment[];
}

export interface EmailAttachment {
  name: string;
  contentType: string;
  contentBytes: string; // Base64
}

export interface EmailResult {
  sent: boolean;
  messageId?: string;
  error?: string;
  method: 'graph' | 'fallback';
}

// ── HTML Templates ──
export const EMAIL_TEMPLATES = {
  incidentNotification: (data: { number: string; priority: string; description: string; assignee: string }) => ({
    subject: `[${data.priority}] Incident ${data.number}: ${data.description}`,
    body: `
      <div style="font-family: 'Segoe UI', sans-serif; max-width: 600px;">
        <div style="background: ${data.priority === 'P1' ? '#d13438' : data.priority === 'P2' ? '#ff8c00' : '#107c10'}; color: white; padding: 16px; border-radius: 8px 8px 0 0;">
          <h2 style="margin: 0;">🚨 Incident ${data.number}</h2>
          <p style="margin: 4px 0 0; opacity: 0.9;">Priority: ${data.priority}</p>
        </div>
        <div style="padding: 16px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 8px 8px;">
          <p><strong>Description:</strong> ${data.description}</p>
          <p><strong>Assigned To:</strong> ${data.assignee}</p>
          <p style="color: #666; font-size: 12px;">This notification was sent by ITSM Operations Digital Worker (Alex IT Ops)</p>
        </div>
      </div>`,
  }),

  shiftHandover: (data: { period: string; summary: string; openIncidents: number; pendingChanges: number }) => ({
    subject: `[Shift Handover] ${data.period} — ${data.openIncidents} open incidents`,
    body: `
      <div style="font-family: 'Segoe UI', sans-serif; max-width: 700px;">
        <div style="background: #0078d4; color: white; padding: 16px; border-radius: 8px 8px 0 0;">
          <h2 style="margin: 0;">📋 Shift Handover Briefing</h2>
          <p style="margin: 4px 0 0; opacity: 0.9;">${data.period}</p>
        </div>
        <div style="padding: 16px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 8px 8px;">
          <div style="display: flex; gap: 16px; margin-bottom: 16px;">
            <div style="background: #f3f2f1; padding: 12px; border-radius: 4px; flex: 1; text-align: center;">
              <div style="font-size: 24px; font-weight: bold;">${data.openIncidents}</div>
              <div style="color: #666;">Open Incidents</div>
            </div>
            <div style="background: #f3f2f1; padding: 12px; border-radius: 4px; flex: 1; text-align: center;">
              <div style="font-size: 24px; font-weight: bold;">${data.pendingChanges}</div>
              <div style="color: #666;">Pending Changes</div>
            </div>
          </div>
          <div>${data.summary}</div>
          <p style="color: #666; font-size: 12px; margin-top: 16px;">Generated by ITSM Operations Digital Worker</p>
        </div>
      </div>`,
  }),

  approvalRequest: (data: { title: string; description: string; approvalUrl: string; requester: string }) => ({
    subject: `[Approval Required] ${data.title}`,
    body: `
      <div style="font-family: 'Segoe UI', sans-serif; max-width: 600px;">
        <div style="background: #8764b8; color: white; padding: 16px; border-radius: 8px 8px 0 0;">
          <h2 style="margin: 0;">⏳ Approval Required</h2>
        </div>
        <div style="padding: 16px; border: 1px solid #e0e0e0; border-top: none; border-radius: 0 0 8px 8px;">
          <p><strong>${data.title}</strong></p>
          <p>${data.description}</p>
          <p><strong>Requested by:</strong> ${data.requester}</p>
          <a href="${data.approvalUrl}" style="display: inline-block; background: #0078d4; color: white; padding: 10px 24px; border-radius: 4px; text-decoration: none; margin-top: 8px;">Review & Approve</a>
        </div>
      </div>`,
  }),
} as const;

// ── Initialization ──

function getGraphClient(): Client | null {
  if (graphClient) return graphClient;
  if (!GRAPH_SENDER) {
    console.warn('[GraphMail] GRAPH_MAIL_SENDER not configured');
    return null;
  }

  try {
    const credential = new DefaultAzureCredential();
    const authProvider = new TokenCredentialAuthenticationProvider(credential, { scopes: GRAPH_SCOPES });
    graphClient = Client.initWithMiddleware({ authProvider });
    console.log('[GraphMail] Microsoft Graph client initialized');
    return graphClient;
  } catch (err) {
    console.error('[GraphMail] Failed to initialize Graph client:', (err as Error).message);
    return null;
  }
}

// ── Send Email ──

export async function sendEmail(message: EmailMessage): Promise<EmailResult> {
  const client = getGraphClient();
  
  if (!client || !GRAPH_SENDER) {
    console.warn('[GraphMail] Graph not configured, logging email instead');
    console.log(`[GraphMail:Fallback] To: ${message.to.join(', ')} | Subject: ${message.subject}`);
    return { sent: false, error: 'Graph Mail not configured', method: 'fallback' };
  }

  try {
    const graphMessage: Record<string, unknown> = {
      message: {
        subject: message.subject,
        body: {
          contentType: message.isHtml !== false ? 'HTML' : 'Text',
          content: message.body,
        },
        toRecipients: message.to.map(email => ({
          emailAddress: { address: email },
        })),
        ccRecipients: (message.cc || []).map(email => ({
          emailAddress: { address: email },
        })),
        importance: message.importance || 'normal',
        isReadReceiptRequested: message.requestReadReceipt || false,
        attachments: (message.attachments || []).map(a => ({
          '@odata.type': '#microsoft.graph.fileAttachment',
          name: a.name,
          contentType: a.contentType,
          contentBytes: a.contentBytes,
        })),
      },
      saveToSentItems: true,
    };

    await client.api(`/users/${GRAPH_SENDER}/sendMail`).post(graphMessage);
    
    console.log(`[GraphMail] Sent to ${message.to.join(', ')}: ${message.subject}`);
    return { sent: true, method: 'graph' };
  } catch (err) {
    const errorMsg = (err as Error).message;
    console.error('[GraphMail] Send failed:', errorMsg);
    return { sent: false, error: errorMsg, method: 'graph' };
  }
}

// ── Convenience Functions ──

export async function sendIncidentNotification(
  to: string[],
  incident: { number: string; priority: string; description: string; assignee: string },
): Promise<EmailResult> {
  const template = EMAIL_TEMPLATES.incidentNotification(incident);
  return sendEmail({ to, ...template, isHtml: true, importance: incident.priority === 'P1' ? 'high' : 'normal' });
}

export async function sendShiftHandover(
  to: string[],
  data: { period: string; summary: string; openIncidents: number; pendingChanges: number },
): Promise<EmailResult> {
  const template = EMAIL_TEMPLATES.shiftHandover(data);
  return sendEmail({ to, ...template, isHtml: true });
}

export async function sendApprovalRequest(
  to: string[],
  data: { title: string; description: string; approvalUrl: string; requester: string },
): Promise<EmailResult> {
  const template = EMAIL_TEMPLATES.approvalRequest(data);
  return sendEmail({ to, ...template, isHtml: true, importance: 'high' });
}

// ── Status ──

export function getGraphMailStatus(): { enabled: boolean; sender: string } {
  return {
    enabled: !!GRAPH_SENDER && !!getGraphClient(),
    sender: GRAPH_SENDER || 'not-configured',
  };
}
